"""bolao models and enviado flag

Revision ID: 8c0e5db4a48f
Revises: b42b3e231695
Create Date: 2025-10-05 11:37:02.780264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0e5db4a48f'
down_revision = 'b42b3e231695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predicao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enviado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predicao', schema=None) as batch_op:
        batch_op.drop_column('enviado')

    # ### end Alembic commands ###
